### ISSUE TITLE
Apks  xAPK Can I use it?

### ISSUE THREAD

**Issue by dongzhaosheng73** [solrudev/SimpleInstaller#4]
Apks  xAPK Can I use it?

**Comment by solrudev** [comment]
You can install split packages from zipped files if you unpack them before passing each APK to SimpleInstaller. The alternative would be implementing an `ApkSource` for a zip entry (you can just stub `getUri()` because it's used only on Android <5.0, and split packages are only availbale on Android ≥5.0).
